# Generated by Django 6.0.2 on 2026-05-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', '教师'), ('student', '学生'), ('assistant', '助教'), ('admin', '管理员')], default='student', max_length=10),
        ),
    ]
